# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mattias/openkorp-logic-dronestate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mattias/openkorp-logic-dronestate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"openkorp-logic-dronestate\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mattias/openkorp-logic-dronestate/CMakeFiles /home/mattias/openkorp-logic-dronestate/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mattias/openkorp-logic-dronestate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openkorp-logic-dronestate

# Build rule for target.
openkorp-logic-dronestate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openkorp-logic-dronestate
.PHONY : openkorp-logic-dronestate

# fast build rule for target.
openkorp-logic-dronestate/fast:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate.dir/build.make CMakeFiles/openkorp-logic-dronestate.dir/build
.PHONY : openkorp-logic-dronestate/fast

#=============================================================================
# Target rules for targets named openkorp-logic-dronestate-core

# Build rule for target.
openkorp-logic-dronestate-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openkorp-logic-dronestate-core
.PHONY : openkorp-logic-dronestate-core

# fast build rule for target.
openkorp-logic-dronestate-core/fast:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/build
.PHONY : openkorp-logic-dronestate-core/fast

opendlv-standard-message-set.o: opendlv-standard-message-set.cpp.o

.PHONY : opendlv-standard-message-set.o

# target to build an object file
opendlv-standard-message-set.cpp.o:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/opendlv-standard-message-set.cpp.o
.PHONY : opendlv-standard-message-set.cpp.o

opendlv-standard-message-set.i: opendlv-standard-message-set.cpp.i

.PHONY : opendlv-standard-message-set.i

# target to preprocess a source file
opendlv-standard-message-set.cpp.i:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/opendlv-standard-message-set.cpp.i
.PHONY : opendlv-standard-message-set.cpp.i

opendlv-standard-message-set.s: opendlv-standard-message-set.cpp.s

.PHONY : opendlv-standard-message-set.s

# target to generate assembly for a file
opendlv-standard-message-set.cpp.s:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/opendlv-standard-message-set.cpp.s
.PHONY : opendlv-standard-message-set.cpp.s

openkorp-message-set.o: openkorp-message-set.cpp.o

.PHONY : openkorp-message-set.o

# target to build an object file
openkorp-message-set.cpp.o:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/openkorp-message-set.cpp.o
.PHONY : openkorp-message-set.cpp.o

openkorp-message-set.i: openkorp-message-set.cpp.i

.PHONY : openkorp-message-set.i

# target to preprocess a source file
openkorp-message-set.cpp.i:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/openkorp-message-set.cpp.i
.PHONY : openkorp-message-set.cpp.i

openkorp-message-set.s: openkorp-message-set.cpp.s

.PHONY : openkorp-message-set.s

# target to generate assembly for a file
openkorp-message-set.cpp.s:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/openkorp-message-set.cpp.s
.PHONY : openkorp-message-set.cpp.s

src/DroneState.o: src/DroneState.cpp.o

.PHONY : src/DroneState.o

# target to build an object file
src/DroneState.cpp.o:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/src/DroneState.cpp.o
.PHONY : src/DroneState.cpp.o

src/DroneState.i: src/DroneState.cpp.i

.PHONY : src/DroneState.i

# target to preprocess a source file
src/DroneState.cpp.i:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/src/DroneState.cpp.i
.PHONY : src/DroneState.cpp.i

src/DroneState.s: src/DroneState.cpp.s

.PHONY : src/DroneState.s

# target to generate assembly for a file
src/DroneState.cpp.s:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate-core.dir/build.make CMakeFiles/openkorp-logic-dronestate-core.dir/src/DroneState.cpp.s
.PHONY : src/DroneState.cpp.s

src/openkorp-logic-dronestate.o: src/openkorp-logic-dronestate.cpp.o

.PHONY : src/openkorp-logic-dronestate.o

# target to build an object file
src/openkorp-logic-dronestate.cpp.o:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate.dir/build.make CMakeFiles/openkorp-logic-dronestate.dir/src/openkorp-logic-dronestate.cpp.o
.PHONY : src/openkorp-logic-dronestate.cpp.o

src/openkorp-logic-dronestate.i: src/openkorp-logic-dronestate.cpp.i

.PHONY : src/openkorp-logic-dronestate.i

# target to preprocess a source file
src/openkorp-logic-dronestate.cpp.i:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate.dir/build.make CMakeFiles/openkorp-logic-dronestate.dir/src/openkorp-logic-dronestate.cpp.i
.PHONY : src/openkorp-logic-dronestate.cpp.i

src/openkorp-logic-dronestate.s: src/openkorp-logic-dronestate.cpp.s

.PHONY : src/openkorp-logic-dronestate.s

# target to generate assembly for a file
src/openkorp-logic-dronestate.cpp.s:
	$(MAKE) -f CMakeFiles/openkorp-logic-dronestate.dir/build.make CMakeFiles/openkorp-logic-dronestate.dir/src/openkorp-logic-dronestate.cpp.s
.PHONY : src/openkorp-logic-dronestate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... openkorp-logic-dronestate"
	@echo "... openkorp-logic-dronestate-core"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... opendlv-standard-message-set.o"
	@echo "... opendlv-standard-message-set.i"
	@echo "... opendlv-standard-message-set.s"
	@echo "... openkorp-message-set.o"
	@echo "... openkorp-message-set.i"
	@echo "... openkorp-message-set.s"
	@echo "... src/DroneState.o"
	@echo "... src/DroneState.i"
	@echo "... src/DroneState.s"
	@echo "... src/openkorp-logic-dronestate.o"
	@echo "... src/openkorp-logic-dronestate.i"
	@echo "... src/openkorp-logic-dronestate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

